### ISSUE TITLE
Add instruction to change domain in idp-metadata.xml

### ISSUE THREAD

**Issue by irfanhakim-as** [sifulan-access-federation/ifirexman-training#47]
When deploying a Shibboleth IdP, the file `idp-metadata.xml` contains domains that require changes specific to the IdP. An instruction/guide to do this needs to be added.

**Comment by farhansj** [comment]
Hi,

A major restructure to the shibboleth idp helm package was made. So now user can just simply customized their IdP in values.yaml file. The rest will be taken care by the Helm template.
